// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP

//#define SRS_AUTO_BUILD_TS "1458318629"
//#define SRS_AUTO_BUILD_DATE "2016-03-19 00:30:29"
//#define SRS_AUTO_UNAME "Linux centos.server2 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"
//#define SRS_AUTO_USER_CONFIGURE " --prefix=/root/srs --full"
//#define SRS_AUTO_CONFIGURE "--prefix=/root/srs --with-hls --with-hds --with-dvr --with-nginx --with-ssl --with-ffmpeg --with-transcode --with-ingest --with-stat --with-http-callback --with-http-server --with-stream-caster --with-http-api --with-librtmp --with-research --with-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --log-trace"

#undef SRS_EXPORT_LIBRTMP

#if 0
#define SRS_AUTO_EMBEDED_TOOL_CHAIN "normal x86/x64 gcc"

#define SRS_AUTO_HTTP_CORE
#define SRS_AUTO_HTTP_SERVER
#define SRS_AUTO_STREAM_CASTER
#define SRS_AUTO_HTTP_API
#define SRS_AUTO_NGINX
#define SRS_AUTO_DVR
#define SRS_AUTO_HLS
#define SRS_AUTO_HDS
#define SRS_AUTO_HTTP_CALLBACK
#define SRS_AUTO_SSL
#endif
#undef SRS_AUTO_MEM_WATCH
#if 0
#define SRS_AUTO_FFMPEG_TOOL
#define SRS_AUTO_FFMPEG_STUB
#define SRS_AUTO_TRANSCODE
#define SRS_AUTO_INGEST
#define SRS_AUTO_STAT
#endif
#undef SRS_AUTO_GPERF
#undef SRS_AUTO_GPERF_MC
#undef SRS_AUTO_GPERF_MP
#undef SRS_AUTO_GPERF_CP
#undef SRS_AUTO_EMBEDED_CPU
#undef SRS_AUTO_ARM_UBUNTU12
#undef SRS_AUTO_MIPS_UBUNTU12

#define SRS_AUTO_VERBOSE
#define SRS_AUTO_INFO
#define SRS_AUTO_TRACE

#define SRS_AUTO_PREFIX "/root/srs"

#define SRS_AUTO_CONSTRIBUTORS "\
"

#endif

